worlds: default
allow_vanilla_trades: false
currency: emerald
librarian: default
cleric: default
farmer: default
fletcher: default
fisherman: default
shepherd: default
butcher: default
leatherworker: default
armorer: default
toolsmith: default
weaponsmith: default
all_villagers: none
